#!/bin/bash
export G8R_HOME=${G8R_HOME:-"$(cd $(dirname $0); pwd)"}
export G8R_TOOLS="$G8R_HOME/tools"
export G8R_TREE="$G8R_HOME/tree"

COMMAND="$1"
shift
case "$COMMAND" in

    automate)
        exec ${G8R_TOOLS}/automation_runner.py
        ;;

    make)
        ${G8R_TOOLS}/update_variables.py
        cd ${G8R_HOME}/tree
        exec make "$@"
        ;;

    init)
        exec ${G8R_TOOLS}/init.sh
        ;;

    etc-hosts)
        echo "About to update /etc/hosts - sudo may prompt for a password." >&2
        for etc_hosts in ./tree/hosts-*/101_etc-hosts.sh; do
            sudo "${etc_hosts}"
        done
        ;;

    add-domain)
        exec ${G8R_TOOLS}/add-domain.sh "$@"
        ;;

    add-host)
        exec ${G8R_TOOLS}/add-host.sh "$@"
        ;;

    ls)
        cd ${G8R_HOME}/scripts 2>/dev/null && ls -1 *.sh 2>/dev/null || {
            echo "No g8r scripts installed" >&2
            exit 1
        }
        ;;

    run)
        G8R_FORCE=n
        if [ "$1" = "--force" ]; then
            G8R_FORCE=y
            shift
        fi
        G8R_SCRIPT="$1"
        G8R_S_PATH="${G8R_HOME}/scripts/$G8R_SCRIPT"
        shift
        if [ -x "$G8R_S_PATH" ]; then
            cd "${G8R_HOME}" || exit 1
            G8R_TS=$(date +%Y%d%mT%H%M%S)
            G8R_ARCHIVED=logs/"${G8R_TS}-${G8R_SCRIPT}"
            G8R_DONE=logs/RAN.$(md5sum "${G8R_S_PATH}" |cut -b1-32)
            if [ -e "$G8R_DONE" -a "$G8R_FORCE" = "n" ]; then
                echo "Skipped, already ran: ${G8R_SCRIPT}"
            else
                (
                    cp -va "$G8R_S_PATH" "${G8R_ARCHIVED}"
                    bash "${G8R_ARCHIVED}" "$@" && touch "${G8R_DONE}"
                )\
                    2>&1 |tee logs/"${G8R_TS}-${G8R_SCRIPT}.log"
            fi
        else
            echo "Not found: $S_PATH" >&2
            exit 1
        fi
        ;;

    *|help)
        if [ "$COMMAND" = "help" -a "$1" != "" ]; then
            cat "${G8R_HOME}/docs/help/$1.txt" 2>/dev/null && exit 0
            echo "Oops! Topic not found: $1"
            echo "-------------------------- -- --- - - -- -- -  -"
        fi
        cat <<tac
Usage: g8r <command> [...]

This is the Governator! It will curl|bash your servers into shape.

See https://github.com/pagekite/g8r for docs and details.

Commands:
tac
        [ -e "$G8R_HOME/tree/automations.json" ] && cat <<tac
    automate   Run automations defined in \$G8R_HOME/tree/automations.json
tac
        [ -e "$G8R_HOME/tools/add-domain.sh" ] && cat <<tac
    init       Peform basic setup of the Governator Server
    add-domain Add a new domain (run w/o args for help)
    add-host   Add a new host (run w/o args for help)
    make       Rebuild scripts by running make in \$G8R_HOME/tree

    etc-hosts  Update /etc/hosts on this machine using current inventory
    deploy     Deploy a host on the VPS provider of your choice
    backup     Download the most recent backups from a hosts
    metrics    Fetch the metrics/monitoring data from a host
    update     Run \`g8r run --force 900_update.sh\` on a host
    undeploy   Undeploy a host (delete the VPS)
tac
        [ -e "$G8R_HOME/scripts/" ] && cat <<tac
    ls         List available scripts
    run X      Run script X
tac
        cat <<tac

G8R_HOME = $G8R_HOME
tac
        exit 99
esac
